In [24]:
import os
import sys

import pandas as pd
import matplotlib.pyplot as plt
import json

import importlib
import lib.ting_utils
import lib.my_frame
import lib.filter
#importlib.reload(lib.ting_utils)
importlib.reload(lib.filter)
from lib.ting_utils import getTingMeasurementsFromFile
from lib.my_frame import MyFrame
from lib.filter import getFilteredSignal

## APPENDING DATA

In [6]:
# Get file names and paths
path = 'csvs/json_measurements/'
jsons = os.listdir(path)
jsons_paths = [path+j for j in jsons]

In [ ]:
# Collect dataframes
df_list = []
for f in jsons_paths:
    cur_df = getTingMeasurementsFromFile(f)
    df_list.append(cur_df)

In [32]:
# Append all dfs in one big df
df = pd.concat(df_list)
df = df.reset_index(drop=True)

In [33]:
df.head()

,date,time,anchor,relay,rtt
0,2020-03-06,12:32:00.086718,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,57.765485
1,2020-03-06,12:32:22.055969,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,56.701660
2,2020-03-06,12:32:43.788800,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,56.005000
3,2020-03-06,12:33:05.401925,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,48.151975
4,2020-03-06,12:33:26.886681,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,59.939980

In [42]:
#df.to_csv('csvs/all_measurements.csv', index=False)

## ROUNDING TO SECONDS

In [34]:
# Round times to seconds
def time_clean(s):
    if('.' in s):
        return s.split('.')[0]
    else:
        return s
    
times = df['time'].apply(time_clean)

In [36]:
df['time'] = times

In [41]:
df.head()

,date,time,anchor,relay,rtt
0,2020-03-06,12:32:00,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,57.765485
1,2020-03-06,12:32:22,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,56.701660
2,2020-03-06,12:32:43,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,56.005000
3,2020-03-06,12:33:05,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,48.151975
4,2020-03-06,12:33:26,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,59.939980

## EXPLORING RELAY DATA

In [69]:
myFrame = MyFrame('csvs/measurements.csv')

In [70]:
for r in myFrame.getRelays():
    num = myFrame.getRelayData(r).shape[0]
    print("Relay",r,num)

Relay 3DCA95587F917F3F212B598731B97BDB85BFEE92 1420
Relay 6E33D4101DDC6366BE477125068E3D5D2F22C747 1506
Relay 9B2BC7EFD661072AFADC533BE8DCF1C19D8C2DCC 1503
Relay B96B5141004995295FE87DCCE1A54519BD0BB48A 1504
Relay 425835370C1FBE178C21CB53C76672F12BDE091A 1491
Relay 5FB384605F53DCBF1CB02143D318DA3E8EE38A24 1538
Relay 06BBEAA6F73759A1795EB461D39D2AA168F305D1 1519
Relay B32B93C90DCAF0012328A8D55D621D26B186E11A 1484
Relay A3901DDB7799A11E9BAB90BD1DDA734DBA196337 1945
Relay 7E281CD2C315C4F7A84BC7C8721C3BC974DDBFA3 1978
Relay D1C5F5F8FAFA2F98A84753416BF83B83F1282137 1944
Relay 35DA04A92634AF2392CBA6AF158E00B5589A1CFA 1924
Relay 8EF052033309D854D6206A4C30F17AD27C87893E 1929
Relay 22A6BE98D201B101C32661739967BF4DED12EF96 1959
Relay C78AFFEEE320EA0F860961763E613FD2FAC855F5 1968
Relay 0E452A30E7E05744071678E0A059BDDB468930CD 1669
Relay A678DA60A6C7CB746553430D84AF45272ECDDA95 1347
Relay D744A380F4FC34F9D11208A2F9E8C69DD556C376 1961
Relay 414385E0BA88B6F7870C389A60819BB06308E8D0 1253
Relay E4F7869E2E9AF579EC93F5CCB823ECFCB297DA4E 1147
Relay 834C91DEEB2FE4FEFCE55A99C378968FB659115C 1216
Relay 0C2781011D61CCB009459B51158DA6328BA3DB3B 1278
Relay 9BDE2A880F985C80E88F3ACC4446E826DEAC7AD1 1329

In [71]:
myFrame.getRelayData('3DCA95587F917F3F212B598731B97BDB85BFEE92')

,date,time,anchor,relay,rtt
0,2020-03-06,12:32:00,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,57.765485
1,2020-03-06,12:32:22,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,56.701660
2,2020-03-06,12:32:43,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,56.005000
3,2020-03-06,12:33:05,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,48.151975
4,2020-03-06,12:33:26,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,59.939980
...,...,...,...,...,...
8439,2020-03-08,16:48:06,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,55.282715
8440,2020-03-08,16:48:27,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,68.639400
8441,2020-03-08,16:48:48,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,67.708135
8442,2020-03-08,16:49:10,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,59.525485
8443,2020-03-08,16:49:31,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,35.904410

## Save cleaned data to csvs/measurements/raw

In [12]:
mf = MyFrame('csvs/measurements_clean.csv')
sessions = mf.getSessions()

In [14]:
sessions[1].data

,date,time,anchor,relay,rtt,datetime
478,2020-03-07,12:50:43,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,64.909455,2020-03-07 12:50:43
479,2020-03-07,12:51:05,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,44.299955,2020-03-07 12:51:05
480,2020-03-07,12:51:26,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,51.674965,2020-03-07 12:51:26
481,2020-03-07,12:51:47,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,33.128025,2020-03-07 12:51:47
482,2020-03-07,12:52:08,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,63.157920,2020-03-07 12:52:08
...,...,...,...,...,...,...
966,2020-03-07,15:49:09,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,59.263715,2020-03-07 15:49:09
967,2020-03-07,15:49:31,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,61.188335,2020-03-07 15:49:31
968,2020-03-07,15:49:52,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,98.889475,2020-03-07 15:49:52
969,2020-03-07,15:50:14,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,52.814600,2020-03-07 15:50:14
970,2020-03-07,15:50:35,99339F3E68BCCC1391BF14C821D80766FE0C5956,3DCA95587F917F3F212B598731B97BDB85BFEE92,53.371070,2020-03-07 15:50:35

In [20]:
# Save each session in different csv file.
# Name of each file will be first 6 letters of signature + id of session
save_path = 'csvs/measurements/raw/'
relay_dic = {}
count = 0

for s in sessions:
    cur_relay = s.relay
    cur_data = s.data
    session_id = relay_dic.get(cur_relay, 0)
    relay_dic.update({cur_relay : session_id+1})
    
    df_save = cur_data[['datetime', 'relay', 'rtt']]
    df_save.to_csv(save_path + cur_relay[:6] + '_' + str(session_id) + '.csv', index=False)
    count +=1
    
print(count)

57

## Filter data and save to filtered folder

In [25]:
# Get names of csv files to be filtered
file_names = [x for x in os.listdir(save_path) if '.csv' in x]
save_path_filtered = 'csvs/measurements/filtered/'

for f in file_names:
    df = pd.read_csv(save_path+f)
    df['rtt'] = getFilteredSignal(df['rtt'])
    df.to_csv(save_path_filtered + f, index=False)